# Generated by Django 5.2.3 on 2025-06-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photo', verbose_name='사진'),
        ),
    ]
