# Generated by Django 5.2.3 on 2025-06-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
