# Generated by Django 5.2.3 on 2025-06-18 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('preferred_gender', models.CharField(max_length=20)),
                ('dining_style', models.CharField(max_length=20)),
                ('eating_speed', models.CharField(max_length=20)),
                ('meal_purpose', models.CharField(max_length=20)),
                ('dessert', models.CharField(max_length=20)),
                ('preferred_menu', models.JSONField()),
                ('dietary_restrictions', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
