# Generated by Django 5.2.3 on 2025-07-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dietary_restrictions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_menu',
            field=models.JSONField(default=list),
        ),
    ]
