# Generated by Django 5.2.3 on 2025-06-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='user_default_nickname', max_length=30),
            preserve_default=False,
        ),
    ]
