# Generated by Django 5.2.3 on 2025-06-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_nickname'),
        ('accounts', '0003_customuser_nickname'),
    ]

    operations = [
    ]
